"""Changed TEXT to NVARCHAR(MAX)

Revision ID: def105e0425d
Revises: ddbb104b4d0c
Create Date: 2025-02-12 13:55:17.143766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def105e0425d'
down_revision: Union[str, None] = 'ddbb104b4d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
